language: ruby
rvm:
  -  2.6.7

services:
  - mongodb
  - redis-server

install:
  # Install node
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  # Install bower
  - sudo npm install -g bower

before_script:
  # Install bower dependencies
  - bower install
  # Install gems
  - bundle install

script:
  - RAILS_ENV=test
  - bundle exec rspec spec
